//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.localhost {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name getResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get", ReplyAction="*")]
        Control.localhost.getResponse get(Control.localhost.getRequest request);
        
        // CODEGEN: Generating message contract since element name lessonScript from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintString", ReplyAction="*")]
        Control.localhost.PrintStringResponse PrintString(Control.localhost.PrintStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get", Namespace="http://tempuri.org/", Order=0)]
        public Control.localhost.getRequestBody Body;
        
        public getRequest() {
        }
        
        public getRequest(Control.localhost.getRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getRequestBody {
        
        public getRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResponse", Namespace="http://tempuri.org/", Order=0)]
        public Control.localhost.getResponseBody Body;
        
        public getResponse() {
        }
        
        public getResponse(Control.localhost.getResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getResult;
        
        public getResponseBody() {
        }
        
        public getResponseBody(string getResult) {
            this.getResult = getResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintString", Namespace="http://tempuri.org/", Order=0)]
        public Control.localhost.PrintStringRequestBody Body;
        
        public PrintStringRequest() {
        }
        
        public PrintStringRequest(Control.localhost.PrintStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lessonScript;
        
        public PrintStringRequestBody() {
        }
        
        public PrintStringRequestBody(string lessonScript) {
            this.lessonScript = lessonScript;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public Control.localhost.PrintStringResponseBody Body;
        
        public PrintStringResponse() {
        }
        
        public PrintStringResponse(Control.localhost.PrintStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Control.localhost.ArrayOfString PrintStringResult;
        
        public PrintStringResponseBody() {
        }
        
        public PrintStringResponseBody(Control.localhost.ArrayOfString PrintStringResult) {
            this.PrintStringResult = PrintStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : Control.localhost.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Control.localhost.ServiceSoap>, Control.localhost.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Control.localhost.getResponse Control.localhost.ServiceSoap.get(Control.localhost.getRequest request) {
            return base.Channel.get(request);
        }
        
        public string get() {
            Control.localhost.getRequest inValue = new Control.localhost.getRequest();
            inValue.Body = new Control.localhost.getRequestBody();
            Control.localhost.getResponse retVal = ((Control.localhost.ServiceSoap)(this)).get(inValue);
            return retVal.Body.getResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Control.localhost.PrintStringResponse Control.localhost.ServiceSoap.PrintString(Control.localhost.PrintStringRequest request) {
            return base.Channel.PrintString(request);
        }
        
        public Control.localhost.ArrayOfString PrintString(string lessonScript) {
            Control.localhost.PrintStringRequest inValue = new Control.localhost.PrintStringRequest();
            inValue.Body = new Control.localhost.PrintStringRequestBody();
            inValue.Body.lessonScript = lessonScript;
            Control.localhost.PrintStringResponse retVal = ((Control.localhost.ServiceSoap)(this)).PrintString(inValue);
            return retVal.Body.PrintStringResult;
        }
    }
}
